const womensList = [
    {
        id: 0,
        gender: "womens",
        img: "womens_product_01.png",
        rating: 5,
        name: "Product Name 01",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 1,
        gender: "womens",
        img: "womens_product_02.png",
        rating: 4,
        name: "Product Name 02",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 2,
        gender: "womens",
        img: "womens_product_03.png",
        rating: 5,
        name: "Product Name 03",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 3,
        gender: "womens",
        img: "womens_product_04.png",
        rating: 4,
        name: "Product Name 04",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 4,
        gender: "womens",
        img: "product_template.png",
        rating: 3,
        name: "Product Name 05",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 5,
        gender: "womens",
        img: "product_template.png",
        rating: 5,
        name: "Product Name 06",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 6,
        gender: "womens",
        img: "product_template.png",
        rating: 4,
        name: "Product Name 07",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 7,
        gender: "womens",
        img: "product_template.png",
        rating: 3,
        name: "Product Name 08",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
];
