const mensList = [
    {
        id: 1,
        gender: "mens",
        img: "mens_product_01.png",
        rating: 5,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 2,
        gender: "mens",
        img: "mens_product_02.png",
        rating: 4,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 3,
        gender: "mens",
        img: "mens_product_03.png",
        rating: 5,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 4,
        gender: "mens",
        img: "mens_product_04.png",
        rating: 4,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 5,
        gender: "mens",
        img: "product_template.png",
        rating: 3,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 6,
        gender: "mens",
        img: "product_template.png",
        rating: 4,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 7,
        gender: "mens",
        img: "product_template.png",
        rating: 5,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
    {
        id: 8,
        gender: "mens",
        img: "product_template.png",
        rating: 3,
        name: "Product Name",
        discription: "Product Description",
        price: 1230.0,
        info:
            "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
        color: ["lightsalmon", "lightseagreen"],
        size: ["S", "M", "L", "XL", "XXL"],
    },
];
